### ISSUE TITLE
`ChangelogBuilder.getCustomTitle` throws exception

### ISSUE THREAD

**Issue by bassepeder** [MFlisar/changelog#24]
My app uses this library. While it works, I see a lot of noise in my Crashlytics logs in regards to this exception. More specifically, this is the exception:

`Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String f8.a.l' on a null object reference
       at com.michaelflisar.changelog.ChangelogBuilder.getCustomTitle(ChangelogBuilder.java:217)
       at com.michaelflisar.changelog.internal.ChangelogActivity.onCreate(ChangelogActivity.java:55)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`
       
I have not been able to find any solution, so I have simply wrapped my code in a `try-catch` for now.

**Comment by MFlisar** [comment]
Are you only starting the `ChangelogActivity` via following function:

https://github.com/MFlisar/changelog/blob/5b0d479baec221d24fa5612c39cde5c91958cd92/lib/src/main/java/com/michaelflisar/changelog/internal/ChangelogActivity.java#L25-L31

If the line numbers inside your log are correct, it seems like there is no `ChangelogBuilder` found inside the `ChangelogActivity` which can only happen if you start the activity in another way than the code block above would do...

**Comment by bassepeder** [comment]
Right now I am doing this:

```
 try {
                val builder = ChangelogBuilder()
                    .withTitle("App changelog")
                    .withManagedShowOnStart(false)
                    .withRateButton(false)
                    .withMinVersionToShow(0)

                builder.buildAndShowDialog(
                    requireActivity() as? AppCompatActivity,
                    requireContext().isDarkTheme()
                )
            } catch (ex: Exception) {
                Snackbar.make(binding.scrollView, "Failed to open changelog.", Snackbar.LENGTH_SHORT).show()
            }
```
